package com.example.jpademo.data;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

import lombok.Data;

@Entity
@Data
public class User {
	
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY) // since ID is auto-incrementally generated by DB this is needed to prevent errors
	private Integer id;
	private String name;
	private String email;

}
